version: '3'
services:
  frontend:
    image: node:16.3.0-alpine
    working_dir: /app
    depends_on:
      - backend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/:/app
    command: yarn dev

  backend:
    image: node:16.3.0-alpine
    working_dir: /app
    depends_on:
      - db
    networks:
      - app-connect
    environment:
      POSTGRES_HOST: db
      DATABASE_URL: postgres://postgres:12345@db:5432/todo_app
    ports:
      - '5000:5000'
    volumes:
      - ./backend/:/app
    command: yarn start  

  db:
    image: 'postgres:latest'
    restart: always
    container_name: db-todo-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: todo_app
    volumes:
      - pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-connect
volumes:
  pgdata:
    driver: local
networks:
  app-connect:
      driver: bridge