version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    container_name: db-todo-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: todo_app
    volumes:
      - pgdata:/data/postgres
    ports:
      - "5432:5432"
volumes:
  pgdata:
    driver: local